# Generated by Django 3.1.2 on 2020-10-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruposFamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=160)),
                ('apellido_medico', models.CharField(max_length=160)),
                ('fecha_nacimiento_medico', models.DateTimeField()),
                ('correo_medico', models.CharField(max_length=80)),
                ('telefono_medico', models.IntegerField()),
                ('clave_medico', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=160)),
                ('apellido_paciente', models.CharField(max_length=160)),
                ('fecha_nacimiento_paciente', models.DateTimeField()),
                ('correo_paciente', models.CharField(max_length=80)),
                ('telefono_paciente', models.IntegerField()),
                ('clave_paciente', models.CharField(max_length=40)),
                ('grupo_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.gruposfamiliares')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion_reporte', models.CharField(max_length=2000)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pacientes')),
            ],
        ),
        migrations.AddField(
            model_name='medicos',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.roles'),
        ),
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=2000)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pacientes')),
            ],
        ),
        migrations.AddField(
            model_name='gruposfamiliares',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medicos'),
        ),
    ]
